site_name: Open Mfantse
site_url: https://www.mfantse.com

# Repository
repo_name: mfantse/mfantse
repo_url: https://github.com/mfantse/mfantse

# Copyright
copyright: Copyright &copy; 2023 Enoch T. Enchill

plugins:
  - search
  - mkdocstrings

nav:
  - Home: 'index.md'
  - About: 'about.md'
  - 'Learn Mfantse':
    - Introduction: 'learn/index.md'
    - Alphabets: 'learn/alphabets.md'
    - Numbers: 'learn/numbers.md'
    - 'Week Days': 'learn/weekdays.md'
  - Contact: 'contact.md'

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo